services:
  # Main database
  db:
    image: postgres:16
    restart: always
    ports:
      - "9081:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_data:/home/postgres/pgdata/data

  # Authentication management and portal
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    restart: always
    ports:
      - "9082:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev # --import-realm
    volumes:
      - keycloak_data:/opt/keycloak/data
    # configs:
    #   - source: keycloak-realm
    #     target: /opt/keycloak/data/import/impolar.json

  # Temporal server for workflow orchestration
  temporal:
    image: temporalio/auto-setup:1.22.4
    ports:
      - "9083:7233"  # gRPC
      - "9084:8233"  # HTTP
    environment:
      - CASSANDRA_SEEDS=temporal-cassandra
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    depends_on:
      - temporal-cassandra
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  # Cassandra database for Temporal
  temporal-cassandra:
    image: cassandra:4.1.3
    ports:
      - "9085:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=temporal
    volumes:
      - temporal_cassandra_data:/var/lib/cassandra

  # Temporal UI
  temporal-ui:
    image: temporalio/ui:2.20.0
    ports:
      - "9086:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:9086
    depends_on:
      - temporal

volumes:
  pg_data:
  keycloak_data:
  temporal_cassandra_data:
# configs:
#   keycloak-realm:
#     content: |